// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtvglsneskjzhfudqpgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dmdsc25lc2tqemhmdWRxcGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjkwMDEsImV4cCI6MjA2NTk0NTAwMX0.WfeG5KFOyibgFIKkA7IH35R7ViuUbSWlvx-ovx3-drQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);